### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by hackergrrl** [dominictarr/tslide#4]
What are your thoughts on using a markdown-to-terminal renderer for slides rather than formatting them as-is? Something like [marked-terminal](https://github.com/mikaelbr/marked-terminal)?

**Comment by dominictarr** [comment]
I originally wrote this 2 hours before I gave a presentation, and it was several years ago, and marked-terminal probably didn't exist then. I think most of the rendering is okay, but better code highlighting would be good.

**Comment by rafaelrinaldi** [comment]
@noffle We just did some changes including improving support for code display so I'm closing this issue and marking it as resolved. Feel free to open a new issue if you think we can do it better :)

Thanks!
