### ISSUE TITLE
syntax highlighting is unreadable

### ISSUE THREAD

**Issue by ghost** [dominictarr/tslide#5]
I've run into a few presentation where I couldn't read some of the syntax of code in the slides because of assumptions about what colors will be visible under which configurations. I think it would be far simpler to remove syntax highlighting all together to prevent issues from cropping up when you least want anything to go wrong.

**Comment by dominictarr** [comment]
fixed in 1.2.0, with option to disable syntax highlighting, use `--no-highlight`

**Comment by ghost** [comment]
Awesome, thanks!
